default:
  N1: 64
  N2: 32
  N3: 1
  kernel_size1: [1, 4]
  strides1: [1, 2]
  pool_size1: 2
  pool_stride1: 1
  kernel_size2: [1, 2]
  strides2: [1, 2]
  pool_size2: 2
  pool_stride2: 1
  kernel_size3: [1, 2]
  strides3: [1, 1]
  pool_size3: 2
  pool_stride3: 1
  Nfc1: 240
  Nfc2: 240
  dropout1: 0.3
  dropout2: 0.3
