default:
  N1: 128
  N2: 1
  kernel_size1: (1, 2)
  strides1: (1, 2)
  pool_size1: 2
  pool_stride1: 1
  kernel_size2: (1, 2)
  strides2: (1, 2)
  pool_size2: 2
  pool_stride2: 1
  units: 32
  Nfc1: 60
  dropout1: 0.2
  dropout2: 0.2
